export const CHANGE_CURRENT_SONG = 'playerBar/CHANGE_CURRENT_SONG'
export const CHANGE_PLAY_LIST = 'playerBar/CHANGE_PLAY_LIST'
export const CHANGE_CURRENT_INDEX = 'playerBar/CHANGE_CURRENT_INDEX'
export const CHANGE_SEQUENCE = 'playerBar/CHANGE_SEQUENCE'
